djangoProj/djangoProj/apps/articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:article_id>/', views.detail, name = 'detail'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name = 'leave_comment'),
    path('/new_article/', views.new_article, name = 'new_article'),
    path('/new_article_detail/', views.new_article_detail, name = 'new_article_detail'),
    path('/new_article_detail/new_article_create/', views.new_article_create, name = 'new_article_create'),
]

djangoProj/djangoProj/apps/openai_15/urls.py
from django.urls import path

from . import views

app_name = 'openai'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:question_id>/', views.detail, name = 'detail'),
    path('<int:question_id>/back2main/', views.back2main, name = 'back2main'),
    path('/new_question/', views.new_question, name = 'new_question'),
    path('/new_question_detail/', views.new_question_detail, name = 'new_question_detail'),
    path('/new_question_detail/new_question_ask/', views.new_question_ask, name = 'new_question_ask'),
]

djangoProj/djangoProj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('openai/', include('openai_15.urls')),
]

djangoProj/djangoProj/apps/articles/models.py
import datetime
from django.db import models
from django.utils import timezone


class Article(models.Model):
    a_title = models.CharField("name of the article", max_length = 200)
    a_content = models.TextField("articles text")
    a_pub_dt = models.DateTimeField('public date')

    def __str__(self):
        return self.a_title

    def was_pb_recently(self):
        return self.a_pub_dt >= (timezone.now() - datetime.timedelta(days=7))

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

class Comment(models.Model):
    a_id = models.ForeignKey(Article, on_delete = models.CASCADE)
    c_au_name = models.CharField('name of an  author', max_length = 50)
    c_content = models.TextField('comments text')

    def __str__(self):
        return (f"{self.c_au_name} - {self.c_content}")

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

djangoProj/djangoProj/apps/openai_15/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    q_name = models.CharField("name of the question", max_length = 200)
    q_request = models.TextField("question request text")
    q_response = models.TextField("question response(answer) text", null=True)
    q_date_req = models.DateTimeField('request date')
    q_date_res = models.DateTimeField('response date', null=True)

    def __str__(self):
        return self.q_name

    def was_asked_recently(self):
        return self.q_date_req >= (timezone.now() - datetime.timedelta(days=7))

    class Meta:
        verbose_name = 'Question to AI'
        verbose_name_plural = 'Questions to AI'

djangoProj/djangoProj/apps/articles/views.py
"""from django.http import HttpResponse

def index(request):
    return HttpResponse("Done! Check more later!")"""
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect
from .models import Article
from django.urls import reverse
from django.utils import timezone

def index(request):
    latest_articles_list = Article.objects.order_by('-a_pub_dt')[:6]
    return render(request, 'articles/list.html', {'latest_articles_list': latest_articles_list})

def detail(request, article_id):
    try:
        a = Article.objects.get(id = article_id)
    except:
        raise Http404("Statements was not found")

    latest_comments_list = a.comment_set.order_by('-id')[:10]

    return render(request, 'articles/detail.html', {'article':a, 'latest_comments_list':latest_comments_list})

def leave_comment(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Statements was not found")

    a.comment_set.create(c_au_name=request.POST['name'], c_content=request.POST['text'])

    return HttpResponseRedirect( reverse('articles:detail', args = (a.id,)) )

def new_article(request):
    return HttpResponseRedirect( reverse('articles:new_article_detail', ))

def new_article_detail(request):
    try:
        time = timezone.now()
    except:
        raise Http404("Statements was not found")

    return render(request, 'articles/new_article_detail.html', {'curtime': time})

def new_article_create(request):
    Article.objects.create(a_title=request.POST['title'], a_content=request.POST['content'], a_pub_dt=timezone.now())

    return HttpResponseRedirect( reverse('articles:index', ))

djangoProj/djangoProj/apps/openai_15/views.py
"""from django.http import HttpResponse

def index(request):
    return HttpResponse("Done! Check more later!")"""
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect
from .models import Question
from django.urls import reverse
from django.utils import timezone
import openai
API_KEY = open("API_KEY.txt", "r").read()
ORG_KEY = open("ORG_KEY.txt", "r").read()
openai.organization = ORG_KEY
openai.api_key = API_KEY

def index(request):
    latest_questions_list = Question.objects.order_by('-q_date_req')[:6]
    return render(request, 'openai_15/list.html', {'latest_questions_list': latest_questions_list})

def detail(request, question_id):
    try:
        q = Question.objects.get(id = question_id)
    except:
        raise Http404("Question was not found")

    return render(request, 'openai_15/detail.html', {'Question': q})

def back2main(request, question_id):
    return HttpResponseRedirect(reverse('openai:index',))

def new_question(request):
    return HttpResponseRedirect( reverse('openai:new_question_detail', ))

def new_question_detail(request):
    try:
        time = timezone.now()
    except:
        raise Http404("Statements was not found")

    return render(request, 'openai_15/new_question_detail.html', {'curtime': time})

def new_question_ask(request):
    a = Question.objects.create(q_name=request.POST['title'], q_request=request.POST['content'], q_date_req=timezone.now())

    airesponse = openai.ChatCompletion.create(
        model='gpt-3.5-turbo',
        messages=[
            {"role": "user", "content": request.POST['content']}
        ]
    )

    additional_response = airesponse['choices'][0]['message']['content']
    a.q_response = additional_response.strip("\n").strip()
    a.q_date_res = timezone.now()
    a.save()

    return HttpResponseRedirect(reverse('openai:detail', args=(a.id,)))

djangoProj/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}{{article.a_title}}{% endblock %}

{% block content %}

    <h2>{{ article.a_title }}</h2>
    <p>{{ article.a_content }}</p>
    <em>{{ article.a_pub_dt }}</em><br>
    {% if article.was_pb_recently %}
        <p style="color:red;">It is a new statement!</p>
    {% endif %}
    <hr>

    {% if latest_comments_list %}
        {% for c in latest_comments_list %}
            <p>
                <strong>{{ c.c_au_name }}</strong>
                <p>{{ c.c_content }}</p>
            </p>
        {% endfor %}
    {% else %}
    Comments are not found :(
        Be The First!
    {% endif %}

    <hr>

    <form action="{% url 'articles:leave_comment' article.id %}" method="POST">

        {% csrf_token %}

        <input type="text" required placeholder="Your name" name="name"><br>
        <textarea name="text" required="" placeholder="Commentary text" cols="30" rows="10"></textarea><br>
        <button type="submit">Leave comment</button>
    </form>
{% endblock %}

djangoProj/templates/articles/list.html
{% extends 'base.html' %}

{% block title %}Last Statements{% endblock %}

{% block content %}

    {% if latest_articles_list %}

        {% for a in latest_articles_list %}
            <a href="{% url 'articles:detail' a.id %}">{{ a.a_title }}</a><br>
        {% endfor %}

	{% else %}
        No relevant statements :(
    {% endif %}

    <br>
    <br>
    <br>
    <br>
    <br>
    <form action="{% url 'articles:new_article' %}" method="POST">

        {% csrf_token %}
        <button type="submit">Create article</button>
    </form>
{% endblock %}

djangoProj/templates/articles/new_article_detail.html
{% extends 'base.html' %}

{% block title %}{{article.a_title}}{% endblock %}

{% block content %}

    <h2>Create new article!</h2>
    <p>{{ curtime }}</p><br><br>

    <form action="{% url 'articles:new_article_create' %}" method="POST">

        {% csrf_token %}

        <input type="text" required placeholder="Article Title" name="title"><br>
        <textarea name="content" required="" placeholder="Article content" cols="150" rows="50"></textarea><br>
        <button type="submit">Confirm article</button>
    </form>

{% endblock %}

djangoProj/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}Site Test{% endblock %}</title>
</head>
<body>

	{% block content %}{% endblock %}

</body>
</html>

djangoProj/templates/openai_15/detail.html
{% extends 'base.html' %}

{% block title %}{{Question.q_name}}{% endblock %}

{% block content %}

    <h2>{{ Question.q_name }}</h2>
    <p>{{ Question.q_request }}</p>
    <p>{{ Question.q_response }}</p>
    <em>{{ Question.q_date_req }}</em><br>
    <em>{{ Question.q_date_res }}</em><br>
    {% if Question.was_asked_recently %}
        <p style="color:red;">It is a new question!</p>
    {% endif %}
    <hr>
    <form action="{% url 'openai:back2main'  Question.id %}" method="POST">

        {% csrf_token %}

        <button type="submit">Back to main</button>
    </form>
{% endblock %}

djangoProj/templates/openai_15/list.html
{% extends 'base.html' %}

{% block title %}Last Questions{% endblock %}

{% block content %}

    {% if latest_questions_list %}

        {% for q in latest_questions_list %}
            <a href="{% url 'openai:detail' q.id %}">{{ q.q_name }}</a><br>
        {% endfor %}

	{% else %}
        No relevant questions :(
    {% endif %}

    <br>
    <br>
    <br>
    <br>
    <br>
    <form action="{% url 'openai:new_question' %}" method="POST">

        {% csrf_token %}
        <button type="submit">Ask question</button>
    </form>
{% endblock %}

djangoProj/templates/openai_15/new_question_detail.html
{% extends 'base.html' %}

{% block title %}{{question.q_name}}{% endblock %}

{% block content %}

    <h2>Ask new question!</h2>
    <p>{{ curtime }}</p><br><br>

    <form action="{% url 'openai:new_question_ask' %}" method="POST">

        {% csrf_token %}

        <input type="text" required placeholder="Question Name" name="title"><br>
        <textarea name="content" required="" placeholder="Question content" cols="100" rows="10"></textarea><br>
        <button type="submit">Ask!</button>
    </form>

{% endblock %}